### ISSUE TITLE
Perf view weirds out after pressing Refresh

### ISSUE THREAD

**Issue by vient** [bencherdev/bencher#126]
1. Open https://bencher.dev/console/projects/lol/perf
2. Press Refresh (button on page, not browser one)
3. Select everything needed for graph to show
4. If you try now to unset a benchmark, it will instead be added again, each time you press on it

**Comment by epompeii** [comment]
Fix implemented here: https://github.com/bencherdev/bencher/commit/f28ce6cccca3d0e635f4c94f157e182f3bcdf623
