### ISSUE TITLE
REST API docs formatting problems

### ISSUE THREAD

**Issue by vient** [bencherdev/bencher#129]
Checked on Windows in Vivaldi and Edge, looks like this
![image](https://github.com/bencherdev/bencher/assets/7602242/e556b0b8-20fe-4780-983c-94a771b9cfce)

**Comment by epompeii** [comment]
Thanks for reporting this!
It's also present on desktop on Mac, Firefox and Chrome.
Oddly though, it is formatted nicely on Android.

Currently, I'm using Swagger's JS and CSS to display the OpenAPI spec, so I suspect that it's an issue in the latter: https://github.com/bencherdev/bencher/blob/main/services/ui/src/styles/swagger-ui.css

Long term, I want to create a more native experience where URL fragments work, etc, so the better fix here may be an OpenAPI spec viewer implemented in Solid.js.

**Comment by epompeii** [comment]
Completed: https://bencher.dev/docs/api/
