### ISSUE TITLE
Add the ability to select a report from the perf page

### ISSUE THREAD

**Issue by epompeii** [bencherdev/bencher#133]
Currently the perf page starts out with no options selected. There is a lot of friction to go from this start state to a useful plot with actual metrics displayed. Due to the high dimensionality of Bencher, one needs to know the right metric kind + branch + testbed + benchmark(s) combination.

To simplify this, display a list of the most recent reports for the project. Once a report is chosen the branch + testbed + benchmark(s) present in that report should then be auto-selected. It may make sense to limit the date range by default to say one month prior to present. If more than one metric kind was collected in the report, then the user would also need to choose which metric kind they wished to have displayed.

When a user navigates to view a perf page, the most recent report + some heuristic for selecting the metric kind could be used to solve the aforementioned cold start problem. This also probably lines up well with most users' use case, going to check the perf plot for their most recent report.

A thank you to @brainstorm for the idea!

**Comment by vient** [comment]
Related idea: automatically select those perf options that have only one choice. For example, if someone only tests main branch, it will be useful.

Related to this is the ability to remove unused things: I only push latency measurements, not execs/s, removing the latter will permit to automatically choose latency.

**Comment by epompeii** [comment]
@brainstorm and @vient this has been implemented: https://github.com/bencherdev/bencher/releases/tag/v0.3.4

A Report can now be selected on the Perf Page within the Reports tab. The Reports tab is now the default tab. The most recent Report is automatically selected when loading the Perf Page.
A "clear all" button has also been added.

Let me know what you think!
