### ISSUE TITLE
In Perf Plot add clicking on metric to view commit

### ISSUE THREAD

**Issue by epompeii** [bencherdev/bencher#170]

**Comment by GitGab19** [comment]
I don't know if it's the perfect place to comment, but it would be nice to have also the benchmark name in every metric popup (when hovering with mouse).

**Comment by epompeii** [comment]
Definitely!

It may also be useful to include the testbed as well, if a user is comparing the same benchmark across different testbeds.

**Comment by bbannier** [comment]
I'd also be interest in easier ways to get access to metadata of single benchmark results from a plot. Right now the commit SHA is shown in a point hover, but there is no easy way to copy it to pivot to the commit on the command line (getting directly to the commit in e.g., GitHub might also be interesting, but IMO that would not be as generally useful).

**Comment by epompeii** [comment]
@GitGab19 and @bbannier I have implemented a way to do this.
You can now click on any Metric in the Perf Plot (the round dots), and it will show you a detailed view for that Metric. For example, [this is a recent Metric](https://bencher.dev/perf/bencher/metrics/7b3c9018-9b8f-4dd7-b473-d04fb0d7fa42?back=L3BlcmYvYmVuY2hlcj9rZXk9dHJ1ZSZyZXBvcnRzX3Blcl9wYWdlPTQmYnJhbmNoZXNfcGVyX3BhZ2U9OCZ0ZXN0YmVkc19wZXJfcGFnZT04JmJlbmNobWFya3NfcGVyX3BhZ2U9OCZwbG90c19wZXJfcGFnZT04JnJlcG9ydHNfcGFnZT0xJmJyYW5jaGVzX3BhZ2U9MSZ0ZXN0YmVkc19wYWdlPTEmYmVuY2htYXJrc19wYWdlPTEmcGxvdHNfcGFnZT0xJnJlcG9ydD01NDAyODE3OC02MjQ3LTQ0YmYtOTI5YS01ZDlmMTFkMjk4MTUmYnJhbmNoZXM9NjE5ZDE1ZWQtMGZiZC00Y2NiLTg2Y2ItZmRkZjMxMjRkYTI5JnRlc3RiZWRzPTBkOTkxYWFjLWIyNDEtNDkzYS04YjBmLThkNDE0MTk0NTVkMiZiZW5jaG1hcmtzPWU5M2IzZDcxLTg0OTktNGZhZS1iYjdjLTRlNTQwYjc3NTcxNCUyQzNiZmQ1ODg3LTgzZWMtNGU2Mi04NjkwLTAyODU1YTM4ZmJjOSUyQzM1MjVmMTc3LWZjOGYtNGE5Mi1iZDJmLWRkYTdjNGUxNTY5OSUyQzU2NTVlZDJhLTNlNDUtNDYyMi1iZGJkLTM5Y2RkOTgzN2FmOCUyQzFkYjIzZTkzLWY5MDktNDBhYS1iZjQyLTgzOGNjN2FlMDVmNSZtZWFzdXJlcz00MzU4MTQ2Yi1iNjQ3LTQ4NjktOWQyNC1iZDIyYmIwYzQ5YjUmc3RhcnRfdGltZT0xNzE2NDY0OTQ3MDAwJmVuZF90aW1lPTE3MTkwNTcwNjEwMDAmY2xlYXI9dHJ1ZQ==).

If you have your Project's `url` set to a GitHub repository then it will turn the git hash in the Metric view into a link auto-magically. For example, the Bencher project has its `url` set to https://github.com/bencherdev/bencher, and the hash in the example above is a link to the commit on GitHub.

Please, let me know what you think!

**Comment by epompeii** [comment]
Completed: https://bencher.dev/docs/reference/changelog/#v0414

Feel free to keep the discussion going here though. I'm more than happy to refine things and make breakout tasks.

**Comment by GitGab19** [comment]
Awesome @epompeii 👏 
I will take a look at it asap, thank you!
