### ISSUE TITLE
Add a `--quiet` flag to CLI

### ISSUE THREAD

**Issue by epompeii** [bencherdev/bencher#182]

**Comment by epompeii** [comment]
Done for `bencher run`: https://github.com/bencherdev/bencher/releases/tag/v0.3.23

All other commands already have the same semantics.

**Comment by epompeii** [comment]
Update @Robertorosmaninho there was a breaking change to this work: https://bencher.dev/docs/reference/changelog/#v0419

In order to get just the JSON output as before you now need to use both `--quiet` and `--format json`.

**Comment by Robertorosmaninho** [comment]
Thanks!
