### ISSUE TITLE
Git clone fails on Windows

### ISSUE THREAD

**Issue by aochagavia** [bencherdev/bencher#267]
This is caused by the file `lib/bencher_adapter/tool_output/go/bench/aux.txt`, which has an invalid name (see [here](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file)). Renaming it to `aux2.txt` or anything else fixes the problem (I have validated it by successfully cloning [my modified fork](https://github.com/aochagavia/bencher)).

This effectively means that Windows users are unable to build projects with a dependency on bencher, so it's probably worth fixing soon.

For completeness, below is the current output of git on my Windows 11 machine:

```
Cloning into 'bencher'...
remote: Enumerating objects: 56706, done.
remote: Counting objects: 100% (2468/2468), done.
remote: Compressing objects: 100% (1133/1133), done.
remote: Total 56706 (delta 1345), reused 1930 (delta 1286), pack-reused 54238
Receiving objects: 100% (56706/56706), 15.11 MiB | 3.91 MiB/s, done.
Resolving deltas: 100% (38520/38520), done.
error: invalid path 'lib/bencher_adapter/tool_output/go/bench/aux.txt'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by epompeii** [comment]
Thanks for letting me know.
Apparently this dates back to 1974!
https://www.reddit.com/r/linuxmasterrace/comments/9ukft0/windows_10_still_cant_create_a_file_called_auxtxt/

**Comment by epompeii** [comment]
Fixed: https://github.com/bencherdev/bencher/pull/268
Thank you, again! TIL!
