### ISSUE TITLE
Reversed port order in docker-compose.yml?

### ISSUE THREAD

**Issue by isherman** [bencherdev/bencher#269]
When testing the [Docker Self-Hosted workflow](https://bencher.dev/docs/tutorial/docker/), I was not able to load the Bencher UI in the browser until I reversed the port order on the following line:
https://github.com/bencherdev/bencher/blob/main/docker-compose.yml#L19

This is with Docker version 24.0.2, build cb74dfc.

**Comment by epompeii** [comment]
Great catch! Thank you, @isherman !
It should be `3000:3000`, just like it is here:

https://github.com/bencherdev/bencher/blob/08b55813db4922fc7e9f3d049f928f4251311ed8/docker/local.docker-compose.yml#L26

Fix has been pushed 😃

**Comment by epompeii** [comment]
PS: I'm aware that there is also now an error occurring with the `wasm` modules in the self-hosted/Node build.
I'm currently looking into this.
