### ISSUE TITLE
Show exe name if bencher run fails with "No such file or directory"

### ISSUE THREAD

**Issue by dholroyd** [bencherdev/bencher#335]
I made a mistake where my `bencher run` invocation had two copies of the command line in it,

```
bencher run "cargo bench ci_bench" \
  --branch "$GITHUB_REF_NAME" \
  --err \
  --adapter rust_iai \
  "cargo bench --bench ci_bench"
```

Bencher failed in this case, which makes sense.  The error message produced was,

```
Failed to spawn command: No such file or directory (os error 2)
```

because I didn't spot my error in the command invocation, it took a while to debug this.  If the error message had included the "executable name" it was trying to run, that might have helped me debug quicker, e.g. something like,

```
Failed to spawn command "cargo bench ci_bench" with arguments "cargo bench --bench ci_bench": "cargo bench ci_bench" No such file or directory (os error 2)
```

**Comment by epompeii** [comment]
Completed as a part of `v0.4.3`: https://github.com/bencherdev/bencher/releases/tag/v0.4.3
Thank you for the great suggestion!

This also got me motivated to implement a couple of other DX improvements for the CLI:
- Automatic pwn request detection
- API vs CLI version checking
