### ISSUE TITLE
Investigate why `encrypted-message` slug breaks Netlify

### ISSUE THREAD

**Issue by epompeii** [bencherdev/bencher#369]
A user tried to create a project with the slug `encrypted-message` for https://github.com/RigoOnRails/encrypted-message

For some reason this completely breaks the Netlify hosted version of the Bencher Console:

```
Apr 16, 08:24:16 PM: beb43464 ERROR  Invoke Error 	{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"Error","errorMessage":"C09F453CC37F0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:ssl/record/rec_layer_s3.c:1590:SSL alert number 80\n","code":"ERR_SSL_TLSV1_ALERT_INTERNAL_ERROR","library":"SSL routines","reason":"tlsv1 alert internal error","stack":["Error: C09F453CC37F0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:ssl/record/rec_layer_s3.c:1590:SSL alert number 80",""]},"stack":["TypeError: fetch failed","    at Object.fetch (node:internal/deps/undici/undici:11731:11)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async #renderError (file:///var/task/node_modules/astro/dist/core/app/index.js:352:27)","    at async Module.handler (file:///var/task/node_modules/@astrojs/netlify/dist/ssr-function.js:29:30)","    at async Runtime.handler (file:///var/task/___netlify-bootstrap.mjs:1920:15)","    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1206:26)"]}
```

Both the console and the public perf page completely fail to load: https://bencher.dev/perf/encrypted-message
If a prefix is added to the slug then it works: https://bencher.dev/perf/rust-encrypted-message
However, if a suffix is added to `encrypt-message` then it still fails.
This issue does not appear when testing locally.

This does not appear to be an issue with the backend as the API endpoint works just fine: https://api.bencher.dev/v0/projects/encrypted-message
And the server logs do not register a call to this endpoint when trying to view the project from either the public perf page or the console.

**Comment by RigoOnRails** [comment]
Thank you for looking into this! Changed the slug to `rust-encrypted-message`, https://bencher.dev/perf/rust-encrypted-message

**Comment by RigoOnRails** [comment]
Seems to be any path that begins with `encrypt`:

https://bencher.dev/console/projects/rust-encrypted-message/benchmarks/encrypt-32-byte-payload-deterministic

**Comment by epompeii** [comment]
Update: I think this is an issue with Astro and `i18n` support.
Anything that starts with `en` causes this same behavior.

I actually ran into this recently when trying to create a static route called `engineering`.
Updating the Astro version seemed to fix things though.

**Comment by epompeii** [comment]
@RigoOnRails the update worked. You can now go back to using `encrypted-message` 😃

Fixed in: https://github.com/bencherdev/bencher/releases/tag/v0.4.6

**Comment by RigoOnRails** [comment]
@epompeii Thank you so much!
