### ISSUE TITLE
Make pinned plots page public

### ISSUE THREAD

**Issue by BD103** [bencherdev/bencher#419]
I find the pinned plots page really useful for organizing benchmarks into categories.

<img width="1552" alt="image" src="https://github.com/bencherdev/bencher/assets/59022059/e69d1f18-52fb-40b5-b03b-169852d7b73f">

Unfortunately this page is not public. If another person wanted to see this pinned plots, they would need to scroll down on the Perf page, click "Pinned," then select their desired plot.

<img width="1552" alt="image" src="https://github.com/bencherdev/bencher/assets/59022059/9b4e36a0-af39-497f-8d77-d2d653ee747e">

This is out-of-the-way and hard to find for users not familiar with Bencher. I propose a new page is added at `/plots/[project]` that displays these pinned plots for all public projects. It will be very similar to the console version, but will omit the "Add" button, the sidebar, and the "Create a Perf Plot" section. A link to the public `/perf` page would also be nice! :)

**Comment by epompeii** [comment]
I'm glad that you're finding pinned plots helpful!

> Unfortunately this page is not public. If another person wanted to see this pinned plots, they would need to scroll down on the Perf page, click "Pinned," then select their desired plot.

To clarify, the pinned plots page is not visible to non-authenticated users. If your project is public (like the Bevy project), then any logged in user can see your pinned plots in the console, just like in the first picture.

If the person wanting to see the dashboard is a part of the project, I would highly recommend inviting them to your organization. Then it would be even easier for them to pull up the pinned plots page.

Does that all make sense?

I'm very open to feedback here, and I definitely need to turn the above into docs.

**Comment by BD103** [comment]
> To clarify, the pinned plots page is not visible to non-authenticated users. If your project is public (like the Bevy project), then any logged in user can see your pinned plots in the console, just like in the first picture.
> 
> If the person wanting to see the dashboard is a part of the project, I would highly recommend inviting them to your organization. Then it would be even easier for them to pull up the pinned plots page.

That's interesting, I did not know that! Either way, I was hoping through pinned plots I could better organize the public perf page of Bevy Bencher. When we eventually get more benchmarks, I don't want new users to have to crawl through the UI to see specific portions that they are interested in. (Seeing all of the benchmarks at once can be overwhelming, and certain benchmarks can take a lot longer than others!)

Instead, I was hoping to use pinned plots to organize the public dashboard into categories such as ECS, rendering, file size, and more. This makes it easier to see what aspects of Bevy are improving, and what aspects are regressing.

**Comment by epompeii** [comment]
> When we eventually get more benchmarks, I don't want new users to have to crawl through the UI to see specific portions that they are interested in. (Seeing all of the benchmarks at once can be overwhelming, and certain benchmarks can take a lot longer than others!)

I totally agree! Adding the pinned plots was the first step in this direction.

> Instead, I was hoping to use pinned plots to organize the public dashboard into categories such as ECS, rendering, file size, and more. This makes it easier to see what aspects of Bevy are improving, and what aspects are regressing.

Is there a reason that you do not want to invite these new users to the Bevy project on Bencher?

My current thinking is that there are two main classes of users:

- Power Users: Maintainers and active contributors to a project that care about monitoring the performance. They are the users that the pinned plots and dashboard-like interfaces are designed for. My goal is to give them all the tools that they need in the Bencher Console.
- Casual Users: First time contributors, occasional contributors, and maintainers that don't usually worry about performance. They generally interact with Bencher as [a comment on a pull request](https://bencher.dev/docs/explanation/bencher-run/#--github-actions-github_token). If they have a performance regression, they just click on the link in the PR comment and view what pops up in the Perf Page. My goal is to keep this interface as simple and streamlined as possible for sharing a single plot at a time.

Does that make sense? Do you think I'm missing a class of user?
I'm definitely open to feedback here as we explore this design space. I do appreciate all of the input.

**Comment by BD103** [comment]
That makes a lot of sense, though I'm not sure I want to give everyone admin access. I'll wait for #22, then! :)

**Comment by epompeii** [comment]
@BD103 I've added a new tracking issue to allow users to create multiple organizations: https://github.com/bencherdev/bencher/issues/436

Would that help alleviate your concerns? Separating the Bevy project into a different organization?

My reason for asking is that https://github.com/bencherdev/bencher/issues/22 is slated as a Bencher Plus ie a paid feature.

**Comment by BD103** [comment]
I don't think multiple organizations would be useful in this scenario. Quoting your example above, I want to give the "power users" in the Bevy organization access to the Bencher console without giving them full editing, deletion, and invitation privileges.

For instance, a subject matter expert in rendering may frequently check the console dashboard just for their specific area to ensure there are no new alerts. They have an interest in monitoring performance over time, but they should not have the ability to invite other members to the organization.

This is part of the reason I asked to make pinned plots public. Subject matter experts, and others with an interest in maintaining Bevy's performance, can view an organized history of the performance.

Unfortunately my Bevy-Bencher integration is not official, so it's unlikely to receive funding for Bencher Plus. In this case, I'm probably just going to invite Bevy maintainers to the organization since they both are trusted and will find it useful.

Thanks for the support, and please ask me if you need me to clarify anything! :)

**Comment by epompeii** [comment]
Thank you again, @BD103 for all of the feedback. This helped convince me that the dashboard should be available publicly.

Completed: https://bencher.dev/docs/reference/changelog/#v0421
