### ISSUE TITLE
failure to delete benchmark

### ISSUE THREAD

**Issue by OmarTawfik** [bencherdev/bencher#458]
The UI displays the following error:

> 🐰 Lettuce romaine calm! Failed to delete. Please, try again.

And inspecting dev console, I see:

- Request: `DELETE https://api.bencher.dev/v0/projects/{PROJECT}/benchmarks/{NAME}`
- Status Code: `409 CONFLICT` 
- X-Request-Id: `9e5de9f0-16ab-406b-bbe1-aa8a703b55c5`
- Fly-Request-Id: `01J35GYD2BG4WVZE38TVR6KXDS-sea`

The error is persisting across many retries.

**Comment by epompeii** [comment]
@OmarTawfik sorry you are running into trouble.

I searched for the `X-Request-Id` in the logs and it lead me to [the `slang` project](https://bencher.dev/perf/slang).
It looks like you still have [a Report that uses the ` ======= CALLGRIND =======================================================` benchmark](https://bencher.dev/perf/slang?report=2f6703af-8954-4d3a-b7d2-fde2e87641e2&branches=9ea17978-8ba4-4794-a1f9-8ac593bd4083&testbeds=34ace5be-12c8-40ce-ac13-0626124f3fd2&benchmarks=5a229c8d-928a-4ec7-aec3-c0fbcec3d89b&measures=72d1bd60-802c-46a8-85c2-b67d4079d631&start_time=1718632737000&end_time=1721224954000&clear=true&key=true&reports_per_page=4&branches_per_page=8&testbeds_per_page=8&benchmarks_per_page=8&plots_per_page=8&reports_page=1&branches_page=1&testbeds_page=1&benchmarks_page=1&plots_page=1).

You have to delete all of the Reports and Thresholds that are associated with a Benchmark before you a can delete the Benchmark itself. 

There are two outstanding issues to help make this a bit easier:
- https://github.com/bencherdev/bencher/issues/350
- https://github.com/bencherdev/bencher/issues/438

**Comment by OmarTawfik** [comment]
I see. Thanks for explaining. I can delete the reports first, then delete the benchmark.

> There are two outstanding issues to help make this a bit easier:

I think the main issue here is that the error message didn't tell me what was going on.
But please feel free to triage/close this issue if you are already tracking this somewhere else.

**Comment by epompeii** [comment]
Great!

And yes the error messages could definitely be improved. Current tracking issues:

- https://github.com/bencherdev/bencher/issues/208
- https://github.com/bencherdev/bencher/issues/449
