### ISSUE TITLE
using same numeric format for all values

### ISSUE THREAD

**Issue by OmarTawfik** [bencherdev/bencher#459]
For example, the axis numbers (left column) are correctly separated by commas, but the plot values (highlighted in red) are not.

![image](https://github.com/user-attachments/assets/1c5aa347-6543-4278-8151-4b173abfdea1)

**Comment by epompeii** [comment]
Completed: https://bencher.dev/docs/reference/changelog/#v0431

Note that the new format will always show two decimal places. The example above would therefore render as: `44,656,995.00`.
