### ISSUE TITLE
`--html` flag does not produce an HTML report

### ISSUE THREAD

**Issue by OmarTawfik** [bencherdev/bencher#469]
Command:

```bash
$ bencher run --project slang --adapter rust_iai_callgrind --testbed dev --html --dry-run "cargo bench --package solidity_testing_perf --bench iai"
```

Output:

```log
    Finished `bench` profile [optimized + debuginfo] target(s) in 0.55s
     Running benches/iai/main.rs (target/release/deps/iai-e3ed8af522dbc984)
iai::benchmarks::parser
  Instructions:          5611600497|5611600497      (No change)
  L1 Hits:               8016766577|8016766577      (No change)
  L2 Hits:                  1987968|1987968         (No change)
  RAM Hits:                   71145|71145           (No change)
  Total read+write:      8018825690|8018825690      (No change)
  Estimated Cycles:      8029196492|8029196492      (No change)

Benchmark Harness Results:
iai::benchmarks::parser
  Instructions:          5611600497|5611600497      (No change)
  L1 Hits:               8016766577|8016766577      (No change)
  L2 Hits:                  1987968|1987968         (No change)
  RAM Hits:                   71145|71145           (No change)
  Total read+write:      8018825690|8018825690      (No change)
  Estimated Cycles:      8029196492|8029196492      (No change)

Bencher New Report:
{
  "branch": "OmarTawfik/perf-testing",
  "end_time": "2024-07-29T08:18:59.961981760Z",
  "hash": "7d42b7e710e4794a630f04015f6e4498bb76198d",
  "results": [
    "iai::benchmarks::parser\n  Instructions:          5611600497|5611600497      (No change)\n  L1 Hits:               8016766577|8016766577      (No change)\n  L2 Hits:                  1987968|1987968         (No change)\n  RAM Hits:                   71145|71145           (No change)\n  Total read+write:      8018825690|8018825690      (No change)\n  Estimated Cycles:      8029196492|8029196492      (No change)"
  ],
  "settings": {
    "adapter": "rust_iai_callgrind"
  },
  "start_time": "2024-07-29T08:17:33.268697678Z",
  "testbed": "dev"
}
```

**Comment by epompeii** [comment]
Great catch! The `--html` flag should have a `conflicts_with` constraint for `--dry-run`.

**Comment by OmarTawfik** [comment]
I see. I was trying to see if it would generate an HTML file that can be viewed locally to read the results.
If it was only intended to be used internally for the GitHub PR comments option, and not by users, should it be hidden from docs/`--help`?

**Comment by epompeii** [comment]
> Great catch! The `--html` flag should have a `conflicts_with` constraint for `--dry-run`.

After sleeping on this, I now believe that this should not have a `conflicts_with` constraint. Otherwise, one would have to remove the `--html` flag when using `--dry-run` which is against the design goals of `--dry-run` as mentioned in https://github.com/bencherdev/bencher/issues/468#issuecomment-2256585484.

> I was trying to see if it would generate an HTML file that can be viewed locally to read the results.

Would having a table of the Report results in the UI (https://github.com/bencherdev/bencher/issues/421) be sufficient?
Or do you only want to view the results locally? If so, why?

>  If it was only intended to be used internally for the GitHub PR comments option, and not by users, should it be hidden from docs/`--help`?

It was originally (and still is) used internally. However, I thought it may be worth exposing to users so non-GitHub Actions users could have access to a summary table from the CLI.

**Comment by OmarTawfik** [comment]
> Would having a table of the Report results in the UI (https://github.com/bencherdev/bencher/issues/421) be sufficient?
> Or do you only want to view the results locally? If so, why?

I think I was misled by the help text:

```log
      --html
          Output results as HTML
```

I was expecting an `.html` file that can be opened locally. But I see now that is not the use case.
Maybe we can reword the docs to indicate that it is only a snippet of html to be injected as PR comments? But not a priority of course.

Thanks for the clarification.

**Comment by epompeii** [comment]
> I was expecting an `.html` file that can be opened locally. But I see now that is not the use case.

This totally makes sense as a use case.
My thinking is to update the `--html` flag to be an option that takes an optional file path parameter.

So it would say something like:

> Output results as an HTML file (default: results.html)

Using `--html` would just use the default local path `results.html`. Alternatively, using `--html path/to/results.html` would save the results for at that path. 

While there, it may be worth creating a corresponding `--json` option with the same semantics for the JSON output.

**Comment by OmarTawfik** [comment]
> My thinking is to update the --html flag to be an option that takes an optional file path parameter.
> it may be worth creating a corresponding --json option with the same semantics for the JSON output.

sounds great!

> Using --html would just use the default local path results.html

nit: If there is no use case for a default path (`results.html`), then I suggest (at least as a start) making it required, so that accidentally omitting the path accidentally doesn't pollute the git workspace. If there is, maybe we can use a temp directory instead, and print the temp file path?

**Comment by epompeii** [comment]
Completed: https://bencher.dev/docs/reference/changelog/#v0419

I ended up unifying this feature request with [the existing `--quiet` flag](https://bencher.dev/docs/explanation/bencher-run/#--quiet). If a user desires the final Report to be in HTML format, they can now use [the new `--format html` option](https://bencher.dev/docs/explanation/bencher-run/#--format-format). When combined with the `--quiet` flag, this allows the user to get just the HTML output. It is then up to the user to do as they wish with this isolated output, such as pipe it to another command or save it to a file.

**Comment by OmarTawfik** [comment]
@epompeii Unfortunately I'm not able to see it on the latest release. The usual text log is printed:

```bash
$ bencher --version

bencher 0.4.19
```

```bash
$ BENCHER_API_TOKEN='XXX' bencher run --project slang --adapter rust_iai_callgrind --testbed dev --format html --dry-run "cargo bench --package solidity_testing_perf --bench iai"

    Finished `bench` profile [optimized + debuginfo] target(s) in 40.85s
     Running benches/iai/main.rs (target/release/deps/iai-a1957f35d431ab62)
iai::benchmarks::parser
  Instructions:          4477319576|4477319576      (No change)
  L1 Hits:               6406660261|6406660261      (No change)
  L2 Hits:                  2178875|2178875         (No change)
  RAM Hits:                   70568|70568           (No change)
  Total read+write:      6408909704|6408909704      (No change)
  Estimated Cycles:      6420024516|6420024516      (No change)

Benchmark Harness Results:
iai::benchmarks::parser
  Instructions:          4477319576|4477319576      (No change)
  L1 Hits:               6406660261|6406660261      (No change)
  L2 Hits:                  2178875|2178875         (No change)
  RAM Hits:                   70568|70568           (No change)
  Total read+write:      6408909704|6408909704      (No change)
  Estimated Cycles:      6420024516|6420024516      (No change)

Bencher New Report:
{
  "branch": "perf-test-html",
  "end_time": "2024-08-29T07:55:31.374111131Z",
  "hash": "32a252534bafc900d3f8b4be2b31454ca8b0eaca",
  "results": [
    "iai::benchmarks::parser\n  Instructions:          4477319576|4477319576      (No change)\n  L1 Hits:               6406660261|6406660261      (No change)\n  L2 Hits:                  2178875|2178875         (No change)\n  RAM Hits:                   70568|70568           (No change)\n  Total read+write:      6408909704|6408909704      (No change)\n  Estimated Cycles:      6420024516|6420024516      (No change)"
  ],
  "settings": {
    "adapter": "rust_iai_callgrind"
  },
  "start_time": "2024-08-29T07:53:37.270542509Z",
  "testbed": "dev"
}
```

**Comment by epompeii** [comment]
@OmarTawfik this is the expected output. 

> --format <FORMAT>
>
> Optional: Format for the **final** Report. The default is human.
>
> Possible values:
>
> - human: Human-readable format
> - json: JSON format
> - html: HTML format

[The `--format` option](https://bencher.dev/docs/explanation/bencher-run/#--format-format) only takes effect on the **final** Report (emphasis added above).
But [the `--dry-run` flag] (https://bencher.dev/docs/explanation/bencher-run/#--dry-run) prevents this final Report from being created.

> --dry-run
>
> Optional: Perform a dry run. This will not store any data to the backend. Neither a **Report**, Branch (as detailed in branch selection), nor Testbed will be created.

Does that make sense? Should I add something else to the docs?

**Comment by OmarTawfik** [comment]
I see. Thanks for the clarification. In that case, I have a couple of tiny suggestions if you would like:

1. adding a `clap` `conflicts_with` between them, so that it errors out if both `--format` and `--dry-run` is used.
2. adding an arg (or env var) to specify the file path to write the report to. Because otherwise, users need to parse/extract the report part of the output, as it is surrounded by other text.
