### ISSUE TITLE
Support generating github checks

### ISSUE THREAD

**Issue by sagudev** [bencherdev/bencher#490]
In servo it's normal for developers to run their 'try' builds in personal fork, but with bencher there is no way to get results in such cases. For example we have this report about WPT runs in PRs: https://github.com/servo/servo/pull/33242#issuecomment-2316369615 and this github check: https://github.com/servo/servo/runs/29422122361 for when we cannot report it to PR.

By using `git merge-base upstream/main HEAD` we can obtain last common hash, then fetch bencher.dev for baseline report to compare to.

**Comment by epompeii** [comment]
It _should_ be possible to use Bencher to compare a fork PR against your `main`/base branch: https://bencher.dev/docs/how-to/github-actions/#pull-requests-from-forks

Is there something I'm missing about your workflow though?

**Comment by sagudev** [comment]
> Is there something I'm missing about your workflow though?

CI is run in personal fork and no PR exists yet or even when things already land (are pushed to main) it would be nice to have this data available directly in github via checks.

**Comment by epompeii** [comment]
> CI is run in personal fork and no PR exists yet

Ah, okay! This is a bit tricky then. Are you wanting this to work for a finite set of contributors or for anyone who makes a fork?

In either case, is having contributors create a `draft` PR to compare their benchmarks acceptable?

> even when things already land (are pushed to main) it would be nice to have this data available directly in github via checks.

I'm not sure how this is different than when a GitHub Action runs on `push: main` like in this example: https://bencher.dev/docs/how-to/github-actions/#base-branch

Can you help me understand, what else you are looking for here?

**Comment by epompeii** [comment]
> but instead we can create github check that would contain the report.

Ah! That totally makes sense. Thank you for clarifying.

> If I will have time I will program this myself during weekend.

That would be great. I'm open to a PR that falls back to adding the report as a GitHub check if it isn't being run as a PR. I think it would still be good to log that this case was triggered.

**Comment by epompeii** [comment]
Completed: https://bencher.dev/docs/reference/changelog/#v0424
