### ISSUE TITLE
The branch version hash link should open in _top

### ISSUE THREAD

**Issue by arv** [bencherdev/bencher#509]
The branch version hash link that you get to when you click on a data point on the plot opens the link in a subframe, which isn' allowed by GitHub.

You should add `target="_top"` to it.

**Comment by arv** [comment]
https://github.com/user-attachments/assets/02e9fd1d-49b8-4f64-86e6-85b0ab758fa9

**Comment by epompeii** [comment]
Ah! This is within the `iframe` for the pinned plots. Yes, it would be worth having any links from there open up in a new page.

In the meantime I would recommend using the button on the lower part of the pinned plot to get a full page view. It looks like this:
![Screenshot_20240925-160321.png](https://github.com/user-attachments/assets/6877a365-ff8e-424c-96bc-382559b1e5f6)

**Comment by epompeii** [comment]
Completed: https://bencher.dev/docs/reference/changelog/#v0421

**Comment by epompeii** [comment]
Update, @arv the `iframe`s are now completely removed: https://github.com/bencherdev/bencher/issues/514
