### ISSUE TITLE
Add ability to pass in version to install scripts

### ISSUE THREAD

**Issue by mwasplund** [bencherdev/bencher#515]
I just had a break in our CI builds because the https://bencher.dev/download/install-cli.ps1 pulls in the latest release which introduced a breaking change to the api and we have not updated our api docker image yet. 

Can you add a flag to pass in the target version for the install script. Thanks!

**Comment by epompeii** [comment]
@mwasplund that's a great idea!

I'm open to PRs to allow overriding the target version in the convenience script: https://github.com/bencherdev/bencher/blob/1919a6aef5f35ae45ab5d542b8091d233a760b99/services/cli/templates/install-cli.ps1.j2#L44

Otherwise, I'll try to get to this soon.

**Comment by epompeii** [comment]
Completed: https://bencher.dev/docs/reference/changelog/#v0429

@mwasplund I have added the ability to set the `BENCHER_VERSION`, see the updated docs: https://bencher.dev/docs/how-to/install-cli/#install-cli-with-script

I didn't think about this at the time, but one thing that may be useful for other Bencher Self-Hosted users going forward is that you should always be able to rely on your own version of the install script to default to the correct version. For example, if you had your Bencher Console hosted at `https://bencher.example.com` then you could just use `https://bencher.example.com/download/install-cli.ps1` as your install script.

```powershell
irm https://bencher.example.com/download/install-cli.ps1 | iex
```

This has the added benefit of not requiring coordination between updating your Bencher Self-Hosted instance and landing a PR to bump the CLI version in your CI config.

**Comment by mwasplund** [comment]
Yeah, I realized I could pull the install script from my hosted endpoint too. 😄 Still nice to have this control.
