### ISSUE TITLE
bug: GitHub Summary implementation does not work

### ISSUE THREAD

**Issue by dklassic** [bencherdev/bencher#530]
The latest release 0.4.25 ‘s GitHub Summary does not work atm. Pointed out by @sagudev this is due to the `$GITHUB_STEP_SUMMARY` is actually a path to a file, so the command `echo “Summary” >> $GITHUB_STEP_SUMMARY` actually writes into the appointed file instead of that environment variable.

I can put out a tested PR to fix this as well.

**Comment by sagudev** [comment]
For reference, we talk about it here: https://github.com/servo/servo/pull/33261#issuecomment-2467273321

**Comment by epompeii** [comment]
Completed: https://bencher.dev/docs/reference/changelog/#v0426
