### ISSUE TITLE
bug: PR comment with multiple units of measurement will be format wrongfully

### ISSUE THREAD

**Issue by dklassic** [bencherdev/bencher#533]
Currently a PR comment given by using the --github-action argument will be formatted wrongfully with everything falling under the same unit as shown in [this example](https://github.com/dklassic/servo/pull/4#issuecomment-2451206394). Whereas the [full report](https://bencher.dev/perf/dklassic-servo/reports/c226feba-906c-48e4-9b05-8328274705f8?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=dklassic-servo) does not have this problem.

**Comment by epompeii** [comment]
This is a bug in the HTML summary generation used by the CLI. The Bencher Console (being Typescript) uses a separate implementation to generate a similar looking result.

I'm open to a PR if you can track down this bug.

**Comment by sagudev** [comment]
I think the problem is that we do not pad with enough `<td></td>`: https://github.com/bencherdev/bencher/blob/3fdd05f0ba61b56cb44f42a641fcc743cfeed6ba/lib/bencher_comment/src/lib.rs#L570 will probably need to become u8.

**Comment by epompeii** [comment]
Taking a closer look at this and things are coming back to me. The Rust/PR Comment implementation needs a complete overhaul, so I'm working on that. 

That is, I no longer recommend trying to open a PR for this. Hopefully I'll have it finished soon.

**Comment by epompeii** [comment]
Completed: https://bencher.dev/docs/reference/changelog/#v0427

I rewrote the Rust implementation to use the same general algorithm/control flow as the Typescript implementation. I tested the new version against the BMF JSON output you all are producing, and it seems to have fixed the problem. Let me know if you see anything else though.
