### ISSUE TITLE
Add commit title to report metadata

### ISSUE THREAD

**Issue by jschwe** [bencherdev/bencher#540]
It would be nice to be able to see the commit title when viewing a report in a plot. 
Currently, one needs to copy the version hash and look up the title manually in the project, which is slightly annoying.

If size of the metadata is a concern, then an alternative could be to add a string template to the project (e.g. `https://github.com/bencherdev/bencher/commit/{}`), so that the bencher.dev UI could make the version hash link clickable and redirect to the commit and a web forge such as github or gitlab.

**Comment by epompeii** [comment]
Hey @jschwe thank you for using Bencher!

> It would be nice to be able to see the commit title when viewing a report in a plot.

I agree that this integration would be nice! Definitely open to PRs 😃

> If size of the metadata is a concern, then an alternative could be to add a string template to the project (e.g. https://github.com/bencherdev/bencher/commit/{}), so that the bencher.dev UI could make the version hash link clickable and redirect to the commit and a web forge such as github or gitlab.

This is currently possible (just not well documented, my fault).
If you set your Bencher Project URL to your GitHub project repo URL then your Metrics will auto-magically have links to the commit, just like you described. [See Bencher for example](https://bencher.dev/perf/bencher/metrics/3b5370cc-4e49-4177-a46d-63d499317475?back=L3BlcmYvYmVuY2hlcj9rZXk9dHJ1ZSZyZXBvcnRzX3Blcl9wYWdlPTQmYnJhbmNoZXNfcGVyX3BhZ2U9OCZ0ZXN0YmVkc19wZXJfcGFnZT04JmJlbmNobWFya3NfcGVyX3BhZ2U9OCZwbG90c19wZXJfcGFnZT04JnJlcG9ydHNfcGFnZT0xJmJyYW5jaGVzX3BhZ2U9MSZ0ZXN0YmVkc19wYWdlPTEmYmVuY2htYXJrc19wYWdlPTEmcGxvdHNfcGFnZT0xJnJlcG9ydD04MWFjMjgwZS03ZTZiLTQxZGQtOTc4Yi0xODQwYWYyOWUzODgmYnJhbmNoZXM9ZTIwNzVmMTYtZGEwMy00MjI5LTliNDYtNWI5NmJiMDBjNzdlJmhlYWRzPWUyMDc1ZjE2LWRhMDMtNDIyOS05YjQ2LTViOTZiYjAwYzc3ZSZ0ZXN0YmVkcz0wZDk5MWFhYy1iMjQxLTQ5M2EtOGIwZi04ZDQxNDE5NDU1ZDImYmVuY2htYXJrcz1lOTNiM2Q3MS04NDk5LTRmYWUtYmI3Yy00ZTU0MGI3NzU3MTQlMkMzYmZkNTg4Ny04M2VjLTRlNjItODY5MC0wMjg1NWEzOGZiYzklMkMzNTI1ZjE3Ny1mYzhmLTRhOTItYmQyZi1kZGE3YzRlMTU2OTklMkM1NjU1ZWQyYS0zZTQ1LTQ2MjItYmRiZC0zOWNkZDk4MzdhZjglMkMxZGIyM2U5My1mOTA5LTQwYWEtYmY0Mi04MzhjYzdhZTA1ZjUmbWVhc3VyZXM9NDM1ODE0NmItYjY0Ny00ODY5LTlkMjQtYmQyMmJiMGM0OWI1JnN0YXJ0X3RpbWU9MTczMDMzNjgwNzAwMCZlbmRfdGltZT0xNzMyOTI4ODgyMDAwJmxvd2VyX2JvdW5kYXJ5PWZhbHNlJnVwcGVyX2JvdW5kYXJ5PWZhbHNlJmNsZWFyPXRydWU=).

If you want to make this work on GitLab, you would just need to add a regex to detect the GitLab SaaS URL and probably any `gitlab.domain.tld` here: https://github.com/bencherdev/bencher/blob/ed2e567baea1f9b2fe877bcef1be4f6309dc9eb9/services/console/src/components/console/deck/hand/card/ViewCard.tsx#L275

**Comment by jschwe** [comment]
Thanks a lot for the quick reply - changing the url to the github repo worked perfectly. 
I'll keep you pointer about gitlab in mind, in case I start using bencher for projects on our self-hosted gitlab instance.

It seems that this issue is actually a duplicate of https://github.com/bencherdev/bencher/issues/507 (Sorry, should have checked before), so I'll be closing this one.
