### ISSUE TITLE
bug: Automatic unit scaling does not reflect in GitHub Action reports

### ISSUE THREAD

**Issue by dklassic** [bencherdev/bencher#545]
Currently using `--github-action` to report a summary/check will have the benchmark result reported with unit scaling in place for the numbers but the unit is still marked as the same.

For example:
- [The result here is scaled to be MB but still reported with bytes as unit](https://github.com/dklassic/servo/actions/runs/12485231562/attempts/1#summary-34844827355)
- [The result here is scaled to be KB but still reported with bytes as unit](https://github.com/dklassic/servo/actions/runs/12485231562/attempts/1#summary-34844451543)

**Comment by epompeii** [comment]
Completed: https://bencher.dev/docs/reference/changelog/#v0432

@dklassic thank you for the bug report. I'm sorry I missed this the first time around.
