### ISSUE TITLE
Create a way to map an old Benchmark to a new Benchmark

### ISSUE THREAD

**Issue by epompeii** [bencherdev/bencher#71]
If a user renames a performance regression test or in some cases even just moves its path
this results in Bencher believing it to be a brand new Benchmark.

Create a way to map an old Benchmark to a new Benchmark.

**Comment by Lowpoint** [comment]
> If a user renames a performance regression test or in some cases even just moves its path
> this results in Bencher believing it to be a brand new Benchmark.
> 
> Create a way to map an old Benchmark to a new Benchmark.

**Comment by epompeii** [comment]
https://github.com/bencherdev/bencher/releases/tag/v0.3.3
