### ISSUE TITLE
Add an adapter for `iai`

### ISSUE THREAD

**Issue by epompeii** [bencherdev/bencher#82]
https://www.reddit.com/r/rust/comments/11xhwv3/comment/jd3rfpt/?utm_source=share&utm_medium=web2x&context=3

**Comment by osiewicz** [comment]
I'd be willing to pick this up.
At some point I'd also be interested in integrating a [iai-like lib](https://github.com/osiewicz/calliper) that I'm working on if you'd be ok with that.

**Comment by epompeii** [comment]
That would be great!
It's worth noting that `iai` will be the first multi-metric kind, benchmark harness for Bencher, so there will be some additional considerations to think through.

And definitely! Once `calliper` becomes (relatively) stable, you're welcome to add it. In the mean time, you can just output JSON in the expected format for Bencher to consume.

**Comment by epompeii** [comment]
So multiple metric kinds per benchmark is already supported in the format used in the benchmark harness adapters:
https://github.com/bencherdev/bencher/blob/v0.2.43/lib/bencher_adapter/src/results/adapter_metrics.rs#L14

It's just that none of the adapters have had to use more than one metric kind per benchmark yet, so some of the helper functions/methods and testing infra won't be all that useful for `iai`.

The larger consideration is how to handle these new metric kinds once the adapter has run. Currently, there are only two "default" metric kinds, `latency` and `throughput`. They get added to every project when they're first created:
https://github.com/bencherdev/bencher/blob/v0.2.43/services/api/src/endpoints/organization/projects.rs#L191 

If we're going to be adding `iai` and eventually `calliper` as a supported benchmark harness adapter (ie https://bencher.dev/docs/explanation/adapters) then it should just work out of the box. Just like with `latency` and `throughput`.

However, I'm a bit hesitant to add any more "default" on project creation metric kinds. Most developers know what `latency` and `throughput` mean off the bat, but adding `instructions`, `l1_access`, `l2_access`, `ram_access`, and `est_cycles` to _every_ project seems like it would lead to a lot of user confusion (and an annoyingly long dropdown in the current UI).

And over time, as more profilers may be added this will probably only get worse. See:
https://github.com/rust-lang/rustc-perf/tree/master/collector#profiling

With all that said, I'm leaning towards auto-magically creating the `iai` metric kinds only as needed for the project. That is, they are only added to the project if/when the user runs a report using `iai`.

This is going to be a pretty broad/sweeping change though, so maybe divide an conquer? You can work on the `iai` parser in `bencher_adapter`, and I can handle making sure the necessary metric kinds will exist once the `rust_iai` adapter is used in a report. How does that sound?

**Comment by osiewicz** [comment]
> This is going to be a pretty broad/sweeping change though, so maybe divide an conquer? You can work on the iai parser in bencher_adapter, and I can handle making sure the necessary metric kinds will exist once the rust_iai adapter is used in a report. How does that sound?

That sounds perfect. =)

**Comment by epompeii** [comment]
Support added in `v0.2.46`. Thank you for all of your help, @osiewicz!
